Ping 2688, PING-2791 [MAIN]
BetterSocial/mobileapp pull request #1460
Opened 2023-10-09 12:57 UTC by agit26milan

2023-10-10 09:25 UTC, agit26milan commented
mas @fajarism @arilukmanp @iwangsyah mintol di review ya

2023-10-11 03:48 UTC, fajarism requested changes
Group setting test snapshot is wrong

2023-10-11 03:48 UTC, fajarism commented on __tests__/screens/GroupSetting/GroupSetting.test.js
> +    expect(toJSON).toMatchSnapshot();
should be 
`expect(toJSON()).toMatchSnapshot();`

toJSON should be invoked --> toJSON() so it return the correct snapshot on .snap file

2023-10-11 03:48 UTC, fajarism commented on src/screens/ContactScreen/index.js
> +      console.log(members, 'moon');
remove console.log

2023-10-11 04:39 UTC, fajarism approved these changes

2023-10-11 04:40 UTC, merged