feat: ping 2740 chattab follow
BetterSocial/mobileapp pull request #1498
Opened 2023-10-23 08:17 UTC by arilukmanp

2023-10-24 07:46 UTC, fajarism requested changes

2023-10-24 11:38 UTC, arilukmanp commented on src/screens/ChannelListScreen/index.tsx
> +  };
Done on latest commits mas @fajarism

2023-10-24 11:40 UTC, arilukmanp commented on src/screens/ChannelListScreen/index.tsx
> +  };
Kindly please to review again @fajarism

2023-10-25 01:59 UTC, fajarism approved these changes

2023-10-25 02:05 UTC, merged