feat: ping 2740 chattab d ms
BetterSocial/mobileapp pull request #1527
Opened 2023-10-29 06:48 UTC by arilukmanp

2023-10-30 14:14 UTC, fajarism requested changes

2023-10-30 16:25 UTC, arilukmanp commented on src/screens/ChannelListScreen/hooks/useFollowUser.ts
> +          }
Kindly please to review the latest commit

2023-10-31 13:19 UTC, fajarism commented on types/repo/SignedMessageRepo/SignedPostNotificationData.ts
> +  Group = 2
mas @arilukmanp community should be added as well

2023-10-31 15:00 UTC, fajarism approved these changes

2023-10-31 15:38 UTC, merged